Update model server
eclipse-emfcloud/coffee-editor pull request #358
Opened 2021-04-27 14:22 UTC by sgraband

2021-04-28 09:20 UTC, eneufeld reviewed
what is the reason for the glsp updates? the changes on the model server?

2021-04-28 09:20 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/handler/operation/AbstractCreateEdgeHandler.java
> +		AddCommand addCommand = (AddCommand) AddCommand.create(modelAccess.getEditingDomain(), workflow,
do we need the cast?

2021-04-28 09:20 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/model/WorkflowModelFactory.java
> +		modelAccess.subscribe(new WorkflowModelServerSubscriptionListener(modelState, modelAccess, actionProcessor));
what is the reason to move this code from top to here?

2021-04-28 09:20 UTC, eneufeld commented
@ndoschek can you take a look at the change as you know about current modelserver developments and the GLSP integration?

2021-04-28 09:32 UTC, sgraband commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/handler/operation/AbstractCreateEdgeHandler.java
> +		AddCommand addCommand = (AddCommand) AddCommand.create(modelAccess.getEditingDomain(), workflow,
Yes, because the `create()` method returns a `Command`, while `AddCommandContribution.clientCommand()` requires an `AddCommand`.

2021-05-03 20:32 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/model/WorkflowModelServerSubscriptionListener.java
> +		onFullUpdate(root);
is there no better way?

2021-05-03 20:32 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/model/WorkflowModelFactory.java
> +		modelAccess.subscribe(new WorkflowModelServerSubscriptionListener(modelState, modelAccess, actionProcessor));
can we check whether we can move this up again?

2021-05-12 08:44 UTC, ndoschek requested changes
Looks good to me, thanks Simon!
I noticed one minor thing in the `CoffeeModelServerModule`

2021-05-12 08:44 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.modelserver.app/src/org/eclipse/emfcloud/coffee/modelserver/app/CoffeeModelServerModule.java
> +	}
These lines can be omitted

2021-05-12 08:44 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server.app/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/model/WorkflowModelServerSubscriptionListener.java
> +		onFullUpdate(root);
I guess we can leave that for now, as the modelserver glsp integration will soon be integrated (and there we a provide more general solution for the incremental update)

2021-06-02 10:20 UTC, ndoschek approved these changes
Looks good to me, thanks Simon!

2021-06-02 10:20 UTC, merged