Update to latest version
eclipse-emfcloud/coffee-editor pull request #424
Opened 2022-01-20 16:23 UTC by eneufeld

2022-01-20 16:51 UTC, eneufeld commented
Fix #375 
Fix #405

2022-01-21 13:24 UTC, ndoschek requested changes
Thanks Eugen for the update!
In general, all products still work as expected but I spotted some issues regarding the diagram styling and overall usage of icons:

1. The workflow diagram seems to have styling issues, in my case it looks like this:
![image](https://user-images.githubusercontent.com/47414588/150531706-c5dba5d2-87f7-4c32-af28-124338990471.png)

2. If I run the client build, my `yarn.lock` is updated and the Theia dependencies are downgraded to `1.20.0` due to the resolutions in the main`package.json`. Could you please update either one of them? Thanks!

3. With Theia >= 1.18.0 the usage of `font-awesome` icons was replaced by `codicon`s. In general, to match the style of Theia we should use `codicons` as well wherever possible. E.g. for GLSP, the diagram icon (for the widget tab and the file node in the navigator) was formerly `fa fa-project-diagram` and was replaced by `codicon codicon-type-hierarchy-sub`.
Especially the `Getting started` widget needs an update of its icons. 
But in general, `codicons` do not offer the whole variety of `font-awesome` icons yet, but it would be great to find replacements from the `codicon` set.
See also the current `codicon` catalogue: https://microsoft.github.io/vscode-codicons/dist/codicon.html
![image](https://user-images.githubusercontent.com/47414588/150532909-8700b127-a2b7-44d9-ae1d-bf7bb4999aa2.png)

2022-01-21 14:01 UTC, eneufeld commented
thanks for the review, I will look at the issues

2022-02-07 12:13 UTC, ndoschek requested changes
Thanks a lot for the update Eugen, looks great to me now!

However, i have some minor comments inline and two more general remarks:
- The initial layout of the diagram could be improved imho as it is quite crooked on opening the diagram editor. If using the auto layout feature, moving all nodes into the center of the canvas and deleting the bend points should restore the "old" layout rather quickly. In general we could think about deleting bend points on auto layouting - but maybe in a separate issue, wdyt?
- Please have another look at the changed files and update the headers (esp year range) there (e.g. the `*OperationHandler`s or the client files).

2022-02-07 12:13 UTC, ndoschek commented on web/coffee-workflow-glsp-editor/src/common/workflow-language.ts
> +    iconClass: 'codicon codicon-type-hierarchy-sub',
In this case we cannot use a util function, due to the location in the `common` directory.

2022-02-07 12:13 UTC, ndoschek commented on web/coffee-workflow-glsp/css/temporary_glsp.css
> +/********************************************************************************
Do we still need that?

2022-02-07 12:13 UTC, ndoschek commented on web/coffee-workflow-glsp/src/di.config.ts
> +import '../css/temporary_glsp.css';
Do we still need that?

2022-02-07 13:13 UTC, eneufeld commented on web/.prettierrc.json
> +{
yes I would love to do so in a second step after the update, we must discuss whether we reuse the glsp config or create an emflcoud one, fine by you?

2022-02-07 13:20 UTC, eneufeld commented on web/coffee-workflow-glsp/css/temporary_glsp.css
> +/********************************************************************************
yes, this is not part of glsp 0.9 but was added after the release

2022-02-07 13:20 UTC, eneufeld commented on web/coffee-workflow-glsp/src/di.config.ts
> +import '../css/temporary_glsp.css';
yes, this is not part of glsp 0.9 but was added after the release

2022-02-07 13:29 UTC, ndoschek commented on web/.prettierrc.json
> +{
Yes that sounds good to me!

2022-02-07 17:41 UTC, ndoschek requested changes
Thanks again Eugen, I just spotted some minor oversights, but my requests are mostly resolved, thanks for that!
One comment from before is unresolved: https://github.com/eclipse-emfcloud/coffee-editor/pull/424#discussion_r800571902
Could you have another look? Thanks a lot!

2022-02-07 17:41 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/WorkflowCommandPaletteActionProvider.java
> +					Lists.newArrayList(new DeleteOperation(editorContext.getSelectedElementIds())), "codicon-diff-removed"));
```suggestion
					Lists.newArrayList(new DeleteOperation(editorContext.getSelectedElementIds())), "diff-removed"));
```

2022-02-07 17:41 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/WorkflowCommandPaletteActionProvider.java
> +					Lists.newArrayList(new DeleteOperation(editorContext.getSelectedElementIds())), "codicon-diff-removed"));
```suggestion
					Lists.newArrayList(new DeleteOperation(editorContext.getSelectedElementIds())), "diff-removed"));
```

2022-02-07 17:41 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/WorkflowCommandPaletteActionProvider.java
> +				"codicon-diff-added");
```suggestion
				"diff-added");
```

2022-02-07 17:41 UTC, ndoschek commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/WorkflowCommandPaletteActionProvider.java
> +				"codicon-diff-added");
```suggestion
				"diff-added");
```

2022-02-07 17:41 UTC, ndoschek commented on web/coffee-editor-extension/src/browser/coffee-tree/coffee-tree-label-provider-contribution.ts
> +    [CoffeeModel.Type.AutomaticTask, 'codicon-gear ' + DEFAULT_COLOR],
Please also update the icon strings here. E.g:
```suggestion
    [CoffeeModel.Type.AutomaticTask, 'gear ' + DEFAULT_COLOR],
```

2022-02-07 17:41 UTC, ndoschek commented on web/coffee-editor-extension/src/browser/coffee-tree/coffee-tree-label-provider-contribution.ts
> +    [CoffeeModel.Type.Join, 'codicon-source-control codicon-rotate-270 ' + DEFAULT_COLOR],
Do we even support `Fork` and `Join` nodes? I can see that it is available in the `Coffee.ecore` and on the client side (`coffee-workflow-glsp/src/model.ts`) but we do not offer a creation tool or a `ModelType` on the server side.

2022-02-07 17:41 UTC, ndoschek commented on web/coffee-editor-extension/src/browser/coffee-tree/coffee-tree-label-provider-contribution.ts
> +const UNKNOWN_ICON = 'codicon-circle-slash ' + DEFAULT_COLOR;
```suggestion
const UNKNOWN_ICON = 'circle-slash ' + DEFAULT_COLOR;
```

2022-03-09 21:49 UTC, ndoschek approved these changes
Thanks a lot Eugen, looks great to me now! :tada:

2022-03-10 07:47 UTC, merged