Add model comparison
eclipse-emfcloud/coffee-editor pull request #441
Opened 2022-04-04 09:04 UTC by sgraband

Added coffee-comparison extension, that communicates via @eclipsesource/comparison-extension.
Uses git integration to retrieve head file and compare it with current state.
Update node colors to better display the comparison state.
Tree view can be triggered on the coffee file -> Compare with HEAD.
Graphical view can be triggered on the notation file -> Compare with HEAD.

Resolves #438.

2022-04-08 07:58 UTC, eneufeld requested changes
Why do we need to add web/coffee-comparison/model/org.eclipse.emfcloud.coffee.model-0.1.0-SNAPSHOT.jar ? Can't we take it from the backend build via a copy?
Please also double check headers of new files

2022-04-08 07:58 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/gmodel/FlowFactory.java
> +		if(modelState instanceof WorkflowModelState) {
pull out to util function?

2022-04-08 07:58 UTC, eneufeld commented on backend/plugins/org.eclipse.emfcloud.coffee.workflow.glsp.server/src/org/eclipse/emfcloud/coffee/workflow/glsp/server/gmodel/NodeFactory.java
> +		if(modelState instanceof WorkflowModelState) {
same util function as for flowFactory?

2022-04-08 07:58 UTC, eneufeld commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-configuration.ts
> + * Copyright (c) 2021 EclipseSource and others.
wrong year in header?
the whole header is wrong, we use EPL oR MIT

2022-04-08 07:58 UTC, eneufeld commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-module.ts
> + * Copyright (C) 2022 EclipseSource and others.
header

2022-04-08 07:58 UTC, eneufeld commented on web/coffee-comparison/src/browser/custom-label-provider.tsx
> +                case 'fas fa-plus-circle green':
why do we need to map from font awesome to codicon? why is the value not directly a codicon?

2022-04-08 07:58 UTC, eneufeld commented on web/coffee-comparison/src/node/coffee-comparison-backend-configuration.ts
> +export class CoffeeComparisonBackendConfiguration extends ComparisonExtensionConfiguration {
why do need to add the same ComparisonExtensionConfiguration to frontend and backend?

2022-04-13 09:25 UTC, sgraband commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-configuration.ts
> + * Copyright (c) 2021 EclipseSource and others.
Seems like a few other packages also use this header:
- coffee-server
- coffee-workflow-glsp
- coffee-workflow-glsp-editor
- coffee-welcome-page

Is this intended?

2022-04-13 09:28 UTC, sgraband commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-module.ts
> + * Copyright (C) 2022 EclipseSource and others.
Just to make sure. This is the correct header?
```
/*!
 * Copyright (c) 2022 EclipseSource and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the MIT License which is
 * available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: EPL-2.0 OR MIT
 */
```

2022-04-13 09:31 UTC, sgraband commented on web/coffee-comparison/src/browser/custom-label-provider.tsx
> +                case 'fas fa-plus-circle green':
Because the value is provided by the Java part of the model comparison, where we cannot access the `codicon()` theia method. The extension uses font awesome icons by default to also support older versions of Theia, while we need codicons in the coffee editor, as font awesome icons are not supported anymore.

2022-04-13 09:32 UTC, sgraband commented on web/coffee-comparison/src/node/coffee-comparison-backend-configuration.ts
> +export class CoffeeComparisonBackendConfiguration extends ComparisonExtensionConfiguration {
This is a known limitation of the Model comparison extension atm. There was a ticket created, but it was not prioritized. But i could split them up if you would prefer it that way.

2022-04-13 19:50 UTC, eneufeld commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-configuration.ts
> + * Copyright (c) 2021 EclipseSource and others.
that is also wrong then

2022-04-13 19:51 UTC, eneufeld commented on web/coffee-comparison/src/browser/custom-label-provider.tsx
> +                case 'fas fa-plus-circle green':
GLSP changed the return strings to be compatible with codicon, maybe Nina can help?
Do we need the support of old Theia versions?

2022-04-13 19:52 UTC, eneufeld commented on web/coffee-comparison/src/node/coffee-comparison-backend-configuration.ts
> +export class CoffeeComparisonBackendConfiguration extends ComparisonExtensionConfiguration {
ok, if there is a ticket that is fine.

2022-04-14 10:43 UTC, sgraband commented on web/coffee-comparison/src/browser/custom-label-provider.tsx
> +                case 'fas fa-plus-circle green':
I opened a PR to fix the model-compare extension to use codicons.

2022-04-19 07:35 UTC, eneufeld reviewed
Looks good, only two small remarks.

2022-04-19 07:35 UTC, eneufeld commented on web/coffee-comparison/src/browser/coffee-comparison-frontend-configuration.ts
> +/*!
I think there is an error, the `!` should not be there I assume

2022-04-19 07:35 UTC, eneufeld commented on web/coffee-workflow-glsp-editor/src/browser/diagram/workflow-diagram-manager.ts
> +        if (options && options.widgetOptions && (options.widgetOptions as any).editMode) {
I think we can simplify this to:
`options?.widgetOptions?.editMode` or does it fail because of casts?

2022-04-20 07:07 UTC, sgraband commented on web/coffee-workflow-glsp-editor/src/browser/diagram/workflow-diagram-manager.ts
> +        if (options && options.widgetOptions && (options.widgetOptions as any).editMode) {
We can simplify it to this: `options?.widgetOptions && (options.widgetOptions as any).editMode`. 

`options?.widgetOptions?.editMode` does not work as `editMode` is not part of `WidgetOptions` and you cannot cast a `?` to `any`.

2022-04-21 13:36 UTC, eneufeld submitted a review, later dismissed
Looks good, thank you!
Would it make sense to add a section on how to use this to the readme?

2022-04-22 14:26 UTC, sgraband commented
I added a description for the validation and comparison to the getting started widget.

2022-06-01 07:29 UTC, sgraband commented
I rebased the branch to master, which should resolve the issue, where nodes could not be added anymore. I also created #449 as a follow up, as it is not relevant to this change, but should be fixed next.

2022-07-12 07:45 UTC, sgraband commented on web/coffee-cpp-extension/src/browser/command-contribution.ts
> +        registry.registerCommand(
All the files you commented on are touched because of the `!` in the header (and then formatted).

2022-07-12 07:46 UTC, sgraband commented on web/coffee-cpp-extension/src/browser/command-contribution.ts
> +        registry.registerCommand(
I will split the functionality and the header/formatting changes into two different commits :+1:

2022-07-14 21:09 UTC, eneufeld submitted a review, later dismissed
Looks good. Works well.
Please squash first and third commit into one so that we have two commits in the end. Thank you!

2022-07-15 07:03 UTC, sgraband commented
Thanks for the feedback Eugen! I squashed the third commit into the first one. Could you reapprove?

2022-07-15 07:12 UTC, eneufeld approved these changes

2022-07-18 09:19 UTC, merged